
function shuffleArtists(artists) {
    const shuffled = [...artists];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}


const artistData = [
    { name: 'Maqbool Fida Husain', img: '../images/MagboolHusain.jpg' },
    { name: 'Lucian Freud', img: '../images/LucianFreud.jpg' },
    { name: 'Yang Fudong', img: '../images/YangFudong.jpg' },
    { name: 'Kehinde Wiley', img: '../images/KehindeWiley.jpg' },
    { name: 'Jenny Saville', img: '../images/JennySaville.jpg' },
    { name: 'Frida Kahlo', img: '../images/FridaKahlo.jpg' },
    { name: 'El Anatsui', img: '../images/ElAnatsui.jpg' },
    { name: 'Gerhard Richter', img: '../images/GerhardRichter.jpg' },
    { name: 'Nasreen Mohamedi', img: '../images/NasreenMohamedi.jpg' },
    { name: 'Simphiwe Ndzube', img: '../images/SimphiweNdzube.jpg' },
    { name: 'Francis Bacon', img: '../images/FrancisBacon.jpg' },
    { name: 'Jean-Michel Basquiat', img: '../images/Jean-MichelBasquiat.jpg' },
    { name: 'Michaël Borremans', img: '../images/MichaelBorremans.jpg' },
    { name: 'Lalla Essaydi', img: '../images/LallaEssaydi.jpg' },
    { name: 'Takashi Murakami', img: '../images/TakashiMurakami.jpg' },
    { name: 'David Hockney', img: '../images/DavidHockney.jpg' },
    { name: 'Subodh Gupta', img: '../images/SubodhGupta.jpg' },
    { name: 'Rose Wylie', img: '../images/RoseWylie.jpg' },
    { name: 'Carrie Mae Weems', img: '../images/CarrieMaeWeems.jpg' },
    { name: 'Anselm Kiefer', img: '../images/AnselmKiefer.jpg' },
    { name: 'Wifredo Lam', img: '../images/WifredoLam.jpg' },
    { name: 'Katherine Bradford', img: '../images/KatherineBradford.jpg' },
    { name: 'Yayoi Kusama', img: '../images/YayoiKusama.jpg' },
    { name: 'Jeff Koons', img: '../images/JeffKoons.webp' },
    { name: 'Dayanita Singh', img: '../images/DayanitaSingh.jpg' },
    { name: 'Marlene Dumas', img: '../images/MarleneDumas.jpg' },
    { name: 'Nam June Paik', img: '../images/NamJunePaik.jpg' },
    { name: 'Peter Halley', img: '../images/PeterHalley.webp' },
    { name: 'Amrita Sher-Gil', img: '../images/AmritaSher-Gil.jpg' },
    { name: 'Marina Abramović', img: '../images/MarinaAbramovic.jpg' },
    { name: 'David Hammons', img: '../images/DavidHammons.jpg' },
    { name: 'Xu Bing', img: '../images/XuBing.jpg' },
    { name: 'Gabriel Orozco', img: '../images/GabrielOrozco.jpg' },
    { name: 'Banksy', img: '../images/Banksy.jpg' },
    { name: 'Seydou Keïta', img: '../images/SeydouKeita.jpg' },
    { name: 'Neo Rauch', img: '../images/NeoRauch.jpg' },
    { name: 'Kerry James Marshall', img: '../images/KerryJamesMarshall.jpg' },
    { name: 'Andy Warhol', img: '../images/AndyWarhol.jpg' },
    { name: 'Shirin Neshat', img: '../images/ShirinNeshat.jpg' },
    { name: 'Georg Baselitz', img: '../images/GeorgBaselitz.jpg' },
    { name: 'Pacita Abad', img: '../images/PacitaAbad.jpg' },
    { name: 'Amy Sillman', img: '../images/AmySillman.jpg' },
    { name: 'Diego Rivera', img: '../images/DiegoRivera.jpg' },
    { name: 'Cindy Sherman', img: '../images/CindySherman.jpg' },
    { name: 'Lee Ufan', img: '../images/LeeUfan.jpg' },
    { name: 'Adrian Ghenie', img: '../images/AdrianGhenie.jpg' },
    { name: 'Julie Mehretu', img: '../images/JulieMehretu.jpg' },
    { name: 'Damien Hirst', img: '../images/DamienHirst.jpg' },
    { name: 'Gonkar Gyatso', img: '../images/GonkarGyatso.jpg' },
    { name: 'Rashid Johnson', img: '../images/RashidJohnson.jpg' },
    { name: 'Pablo Picasso', img: '../images/PabloPicasso.jpg' },
    { name: 'Ernesto Neto', img: '../images/ErnestoNeto.jpg' },
    { name: 'Jonas Wood', img: '../images/JonasWood.jpg' },
    { name: 'Yoko Ono', img: '../images/YokoOno.jpg' },
    { name: 'Louise Bourgeois', img: '../images/LouiseBourgeois.jpg' },
    { name: 'Chéri Samba', img: '../images/CheriSamba.jpg' },
    { name: 'Nicole Eisenman', img: '../images/NicoleEisenman.jpg' },
    { name: 'William Kentridge', img: '../images/WilliamKentridge.jpg' },
    { name: 'Jackson Pollock', img: '../images/JacksonPollock.jpg' },
    { name: 'Zarina Hashmi', img: '../images/ZarinaHashmi.jpg' },
    { name: 'Wilhelm Sasnal', img: '../images/WilhelmSasnal.jpg' },
    { name: 'Cai Guo-Qiang', img: '../images/CaiGuo-Qiang.jpg' },
    { name: 'Tracey Emin', img: '../images/TraceyEmin.jpg' },
    { name: 'Aida Muluneh', img: '../images/AidaMuluneh.jpg' },
    { name: 'Dana Schutz', img: '../images/DanaSchutz.jpg' },
    { name: 'Kara Walker', img: '../images/KaraWalker.jpg' },
    { name: 'Richard Diebenkorn', img: '../images/RichardDiebenkorn.jpg' },
    { name: 'Ibrahim El-Salahi', img: '../images/IbrahimEl-Salahi.jpg' },
    { name: 'Cy Twombly', img: '../images/CyTwombly.jpg' },
    { name: 'Mark Bradford', img: '../images/MarkBradford.jpg' },
    { name: 'Avery Singer', img: '../images/AverySinger.jpg' },
    { name: 'Hassan Hajjaj', img: '../images/HassanHajjaj.jpg' },
    { name: 'Zhang Huan', img: '../images/ZhangHuan.jpg' },
    { name: 'Sigmar Polke', img: '../images/SigmarPolke.jpg' },
    { name: 'Raqib Shaw', img: '../images/RaqibShaw.jpg' },
    { name: 'Nick Cave', img: '../images/NickCave.jpg' },
    { name: 'Luc Tuymans', img: '../images/LucTuymans.jpg' },
    { name: 'Vik Muniz', img: '../images/VikMuniz.jpg' },
    { name: 'Ai Weiwei', img: '../images/AiWeiwei.jpg' },
    { name: 'Nalini Malani', img: '../images/NaliniMalani.jpg' },
    { name: 'Yoshitomo Nara', img: '../images/YoshitomoNara.jpg' },
    { name: 'Imran Qureshi', img: '../images/ImranQureshi.jpg' },
    { name: 'Mona Hatoum', img: '../images/MonaHatoum.jpg' }
];

export default shuffleArtists(artistData);